In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import scipy.image as im

ImportError: No module named image

In [58]:
import os
pred_folder = '../../demo/predictions/'
top_folder = '../../demo/top/'

def get_top_frames(pred, thr_first_beat=0.5, n_beats=8, n_top=5):
    corr = np.correlate(pred, np.ones((n_beats,)))
    start = corr*(pred[:len(corr)] >= thr_first_beat)
#     plot(pred)
#     plot(corr)
#     plot(start)
    top = np.argsort(start)
    return top[-n_top:]

for f in os.listdir(pred_folder):
    file_path = os.path.join(pred_folder, f)
    print file_path
    if os.path.isfile(file_path) and file_path.endswith('.csv'):
        pred = np.genfromtxt(file_path, delimiter=',').T
        print pred.shape
        top = get_top_frames(pred, thr_first_beat=0.5, n_beats=8, n_top=5)
        print top
        np.savetxt(os.path.join(top_folder, f), top, delimiter=',')

# get_top_frames(random.randint(0,2,(100,)))

../../demo/predictions/01 Can't Get Enough Of Your Love_prediction.csv
(408,)
[382 381 380 389 400]
../../demo/predictions/01 I Want You [Vocal Version]_prediction.csv
(452,)
[438 437 443 439 444]
../../demo/predictions/01 The Look Of Love_prediction.csv
(960,)
[799 800 801 794 952]
../../demo/predictions/04 (Don't Worry) If There's a Hel_prediction.csv
(828,)
[108 107 106 115 111]
../../demo/predictions/05 It's A Man's Man's World_prediction.csv
(430,)
[212 210   1 213 211]
../../demo/predictions/05 Love on a Two-Way Street_prediction.csv
(482,)
[39 21 22 37 20]
../../demo/predictions/05 Stop, Look, Listen (To Your Heart)_prediction.csv
(659,)
[535 534 533 377 382]
../../demo/predictions/06 Brazilian Rhyme (Interlude)_prediction.csv
(143,)
[39 22  2  1  0]
../../demo/predictions/06 Everybody Is a Star_prediction.csv
(517,)
[11 12 13  6  0]
../../demo/predictions/06 For the Love of Money_prediction.csv
(706,)
[ 21  20  19 697 698]
../../demo/predictions/06 Grandma's Hands_prediction.cs

In [15]:
len(a)

100

In [16]:
len(b)

97